### PR TITLE
fix: change the sidebar to a material ui drawer

### LINKED ISSUE #48: Change filter sidebar to a drawer
**Describe the bug**
The filtering sidebar doesn't look good when imported as a component.

### PR DESCRIPTION
**Pull request by mattbford**
Changed the filter sidebar to a material ui drawer. Much cleaner implementation. Looks and functions better.

Screen Shot 2020-06-18 at 11 33 19 AM

fixes #48

### CODE REVIEW

**Comment by meowsbits** [comment]
Can I get a screenshot?

**Comment by meowsbits** [comment]
Just out of curiosity, why blue-green / yellow-yellow?

**Comment by mattbford** [comment]
> Just out of curiosity, why blue-green / yellow-yellow? (ie What do the colors mean?)

Blue: request
Green: Successful Response
Yellow: rpc. methods 
I think yellow is a good way to distinguish that they are there but likely not what you are looking for

**Pull request merged**
